"""Add_Description_to_ShipStatus

Revision ID: 035b8c6b3d14
Revises: 3c89a3e0b894
Create Date: 2018-12-03 19:36:19.196378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '035b8c6b3d14'
down_revision = '3c89a3e0b894'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ship_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ship_status', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
