"""NotNull_Username_User,Add_client_secret_User

Revision ID: 0f7142142e11
Revises: 19cfcd0e8317
Create Date: 2018-12-12 16:34:35.085995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f7142142e11'
down_revision = '19cfcd0e8317'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_secret', sa.String(length=256), nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('client_secret')

    # ### end Alembic commands ###
