"""Create_Ship_Table

Revision ID: 200d944c86c6
Revises: b3260cd376c0
Create Date: 2018-11-16 01:54:08.282339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '200d944c86c6'
down_revision = 'b3260cd376c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('code', sa.String(length=5), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ship_code'), 'ship', ['code'], unique=False)
    op.create_index(op.f('ix_ship_name'), 'ship', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ship_name'), table_name='ship')
    op.drop_index(op.f('ix_ship_code'), table_name='ship')
    op.drop_table('ship')
    # ### end Alembic commands ###
