"""Add_Capacity_Ship

Revision ID: 30375d8e23dc
Revises: 5402427fdfbf
Create Date: 2018-11-20 21:43:01.263547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30375d8e23dc'
down_revision = '5402427fdfbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ship', sa.Column('capacity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ship', 'capacity')
    # ### end Alembic commands ###
