"""Add_Ship_Status_Link_One2Many_Ships

Revision ID: 3c89a3e0b894
Revises: 505af25c857b
Create Date: 2018-11-23 16:03:29.316831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c89a3e0b894'
down_revision = '505af25c857b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ship_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ship_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ship_status_name'), ['name'], unique=False)

    with op.batch_alter_table('ship', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ship_status_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'ship_status', ['ship_status_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ship', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ship_status_id')

    with op.batch_alter_table('ship_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ship_status_name'))

    op.drop_table('ship_status')
    # ### end Alembic commands ###
