"""Add_Ship_Type_Link_One2Many_Ships

Revision ID: 505af25c857b
Revises: 639976598d91
Create Date: 2018-11-23 10:54:26.727863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '505af25c857b'
down_revision = '639976598d91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ship_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ship_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ship_type_name'), ['name'], unique=False)

    with op.batch_alter_table('ship', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ship_type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'ship_type', ['ship_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ship', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ship_type_id')

    with op.batch_alter_table('ship_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ship_type_name'))

    op.drop_table('ship_type')
    # ### end Alembic commands ###
