"""Fixed date column

Revision ID: 5402427fdfbf
Revises: 200d944c86c6
Create Date: 2018-11-16 14:03:46.690557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5402427fdfbf'
down_revision = '200d944c86c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ship', sa.Column('launch_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ship', 'launch_date')
    # ### end Alembic commands ###
