"""Add_Builder_Link_One2Many_Ships

Revision ID: 639976598d91
Revises: 331e9b9a47a8
Create Date: 2018-11-21 19:46:26.686415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '639976598d91'
down_revision = '331e9b9a47a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('builder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('code', sa.String(length=5), nullable=True),
    sa.Column('date_founded', sa.Date(), nullable=True),
    sa.Column('founder', sa.String(length=40), nullable=True),
    sa.Column('headquarters', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('builder', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_builder_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_builder_name'), ['name'], unique=False)

    with op.batch_alter_table('ship', schema=None) as batch_op:
        batch_op.add_column(sa.Column('builder_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'builder', ['builder_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ship', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('builder_id')

    with op.batch_alter_table('builder', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_builder_name'))
        batch_op.drop_index(batch_op.f('ix_builder_code'))

    op.drop_table('builder')
    # ### end Alembic commands ###
