"""User_client_secret_strlength_128

Revision ID: 750ead51685f
Revises: 13948860312b
Create Date: 2018-12-13 01:56:41.667033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '750ead51685f'
down_revision = '13948860312b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_secret', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('client_secret')

    # ### end Alembic commands ###
