"""Add_Engine_Table

Revision ID: 7c1fe1050867
Revises: 30375d8e23dc
Create Date: 2018-11-20 21:47:33.723635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c1fe1050867'
down_revision = '30375d8e23dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('code', sa.String(length=5), nullable=True),
    sa.Column('power_output', sa.Float(), nullable=True),
    sa.Column('type', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engine_code'), 'engine', ['code'], unique=False)
    op.create_index(op.f('ix_engine_name'), 'engine', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_engine_name'), table_name='engine')
    op.drop_index(op.f('ix_engine_code'), table_name='engine')
    op.drop_table('engine')
    # ### end Alembic commands ###
