"""Ship_Engine_Builder_column_Code_unique_nullable

Revision ID: 8e8d02ab9dd4
Revises: 035b8c6b3d14
Create Date: 2018-12-12 10:28:24.144082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e8d02ab9dd4'
down_revision = '035b8c6b3d14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('builder', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
        batch_op.drop_index('ix_builder_code')
        batch_op.create_index(batch_op.f('ix_builder_code'), ['code'], unique=True)

    with op.batch_alter_table('engine', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
        batch_op.drop_index('ix_engine_code')
        batch_op.create_index(batch_op.f('ix_engine_code'), ['code'], unique=True)

    with op.batch_alter_table('ship', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
        batch_op.drop_index('ix_ship_code')
        batch_op.create_index(batch_op.f('ix_ship_code'), ['code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ship', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ship_code'))
        batch_op.create_index('ix_ship_code', ['code'], unique=False)
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)

    with op.batch_alter_table('engine', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_engine_code'))
        batch_op.create_index('ix_engine_code', ['code'], unique=False)
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)

    with op.batch_alter_table('builder', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_builder_code'))
        batch_op.create_index('ix_builder_code', ['code'], unique=False)
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)

    # ### end Alembic commands ###
