"""Remove_RevokedToken_Table

Revision ID: a820acacb20d
Revises: b9586e96ee77
Create Date: 2018-12-22 23:43:18.798514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a820acacb20d'
down_revision = 'b9586e96ee77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revoked_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_token',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('jti', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='revoked_token_pkey')
    )
    # ### end Alembic commands ###
