"""Add_token_hash_User

Revision ID: b9586e96ee77
Revises: 28fb5b1eaf5d
Create Date: 2018-12-20 16:56:32.260456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9586e96ee77'
down_revision = '28fb5b1eaf5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_hash', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('token_hash')

    # ### end Alembic commands ###
